### ISSUE TITLE
ipaddress validation error 

### ISSUE THREAD

**Issue by jcarapet** [racker/cookbook-cloudmonitoring#66]
I am running the cloud_monitoring cookbook, and trying to enable monitoring on an entity that I host. here is the basic output code. 
```
include_recipe "cloud_monitoring"

cloud_monitoring_entity "#{node.hostname}" do
  ip_addresses        'default' => node[:ipaddress]
  metadata            'environment' => 'dev', :more => 'meta data'
  rackspace_username 'user_blah_blah'
  rackspace_api_key 'thisisn'treal'
  action :create
end
```
I am getting the following output, and I don't have enough knowledge of fog gem to debug the issue. Is this a bug or do you have a suggestion on where to fix it?
```
Recipe: cook_rack_monitoring::default
  * cloud_monitoring_entity[rack-monitor-test1] action create
    
    ================================================================================
    Error executing action `create` on resource 'cloud_monitoring_entity[rack-monitor-test1]'
    ================================================================================
    
    Fog::Rackspace::Monitoring::BadRequest
    --------------------------------------
    [HTTP 400 | .rh-yWd6.h-dfw1-maas-prod-api1.r-9Dm9C2n3.c-82026845.ts-1425396706506.v-e476db8] Validation error for key 'ip_addresses' - Operation is not permitted
    
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/cloud_monitoring/providers/entity.rb:32:in `block in class_from_file'
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/cook_rack_monitoring/recipes/default.rb
    
     12: cloud_monitoring_entity "#{node.hostname}" do
     13:   ip_addresses        'default' => node[:ipaddress]
     14:   metadata            'environment' => 'dev', :more => 'meta data'
     15:   rackspace_username 'user_blah_blah'
     16:   rackspace_api_key 'thisisn'treal'
     17:   action :create
     18: end
     19: # case node['platform_version']
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/cook_rack_monitoring/recipes/default.rb:12:in `from_file'
    
    cloud_monitoring_entity("rack-monitor-test1") do
      action [:create]
      retries 0
      retry_delay 2
      guard_interpreter :default
      cookbook_name "cook_rack_monitoring"
      recipe_name "default"
      ip_addresses {"default"=>"23.253.172.82"}
      metadata {"environment"=>"dev", :more=>"meta data"}
      rackspace_username "user_blah_blah"
      rackspace_api_key "thisisntreal"
      label "rack-monitor-test1"
    end
```

I have also tried passing the username and API as an attribute rather than string, but i can't seem to figure this one out. Is there something I am missing in the documentation?

**Comment by martinb3** [comment]
Added formatting.

**Comment by jcarapet** [comment]
Would you mind elaborating on that a bit? specifically in metadata or agent_id attributes, or do I need to have an additional resource before this? Or are you asking me to gist this? I am willing to do all of the above.

**Comment by jcarapet** [comment]
at this point I have been running the recipes 
- cloud_monitoring::default
- cloud_monitoring::agent
- cloud_monitoring::raxmon

I have been using my username and accounts attributes for

- default['cloud_monitoring']['rackspace_username']
- default['cloud_monitoring']['rackspace_api_key']

I can see that it is setting up the configuration, and that rackspace-monitoring-agent is installed and running on the system fine, but it is not registering with the rackspace cloud account. As it is generating the agent-id automatically, is there another attribute that I need to put in for added formatting?

**Comment by mpycio** [comment]
Hi,
I'm running into same issue right now, I can't see how it was resolved. Additionally when I include cloud_monitoring::agent in the role run_list or in the recipe I get different error:

  Chef::Exceptions::RecipeNotFound
  --------------------------------
  could not find recipe agent_repo.rb for cookbook cloud_monitoring


If I remove .rb from the line that includes that recipe I get past this error:
In agent.rb line 8:
include_recipe 'cloud_monitoring::agent_repo.rb' 
-> to
include_recipe 'cloud_monitoring::agent_repo'


But now different error displays:

  ---------
  No resource, method, or local variable named `retrieve_agent_token' for `Chef::Recipe "agent"'
  
  Cookbook Trace:
  ---------------
    /var/chef/cache/cookbooks/cloud_monitoring/recipes/agent.rb:31:in `from_file'
  
  Relevant File Content:
  ----------------------
  /var/chef/cache/cookbooks/cloud_monitoring/recipes/agent.rb:
  
   24:    if values.to_hash.key? 'agent_token'
   25:      node.set['cloud_monitoring']['agent']['token'] = values['agent_token']
   26:    end
   27:  rescue Exception => e
   28:    Chef::Log.error 'Failed to load rackspace cloud data bag: ' + e.to_s
   29:  end
   30:  
   31>> retrieve_agent_token if node['cloud_monitoring']['agent']['token'].nil?
   32:  
   33:  cloud_monitoring_agent_token node['cloud_monitoring']['agent']['id'] do
   34:    rackspace_username node['cloud_monitoring']['rackspace_username']
   35:    rackspace_api_key node['cloud_monitoring']['rackspace_api_key']
   36:    action :create
   37:  end
   38:  
   39:  package 'rackspace-monitoring-agent' do
   40:    if node['cloud_monitoring']['agent']['version'] == 'latest'

Any help will be much appreciated.

**Comment by jcarapet** [comment]
I resolved it by writing my own cookbook that followed the install script guidelines setup by rackspace monitoring how-to and made it work. The only response I received on my original issue  was a comment that said "added formatting" with no further explanation. Not sure where that comment went to be honest. As I had to write my own and received no follow up, I assumed that this was considered a rtm and a no-fix, so closed it.

On your additional issue I don't have an answer, so I will reopen and see if you can get another response.

**Comment by martinb3** [comment]
FWIW, I added Github Markdown formatting to your issue. That was all I did, hence the 'added formatting.' Your issue was fairly tricky to read without some mono-spacing :)
